package com.rinha.gui;

import java.awt.CardLayout;

public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }
    
    /*
    * Minhas funções para auxiliar na interface
    */
    
    public void trocarTela(String nomeDoCard){
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, nomeDoCard);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        telaInicial = new javax.swing.JPanel();
        botaoSettings = new javax.swing.JButton();
        botaoHelp = new javax.swing.JButton();
        botaoPlay = new javax.swing.JButton();
        labelBackgroundTelaInicial = new javax.swing.JLabel();
        telaDashBoard = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        menuInicial = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botaoPerfil = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        botaoGaloDex = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        telaLoja = new javax.swing.JPanel();
        telaBatalha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("rinha");
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        setSize(getPreferredSize());

        painelPrincipal.setAlignmentX(0.0F);
        painelPrincipal.setAlignmentY(0.0F);
        painelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelPrincipal.setMaximumSize(getPreferredSize());
        painelPrincipal.setMinimumSize(getPreferredSize());
        painelPrincipal.setName(""); // NOI18N
        painelPrincipal.setPreferredSize(getPreferredSize());
        painelPrincipal.setLayout(new java.awt.CardLayout());

        telaInicial.setAlignmentX(0.0F);
        telaInicial.setAlignmentY(0.0F);
        telaInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telaInicial.setMaximumSize(getPreferredSize());
        telaInicial.setMinimumSize(getPreferredSize());
        telaInicial.setName(""); // NOI18N
        telaInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botaoSettings.png"))); // NOI18N
        botaoSettings.setContentAreaFilled(false);
        telaInicial.add(botaoSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));

        botaoHelp.setBackground(new java.awt.Color(228, 56, 82));
        botaoHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoHelp.setForeground(new java.awt.Color(238, 240, 242));
        botaoHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botaoHelp.png"))); // NOI18N
        botaoHelp.setContentAreaFilled(false);
        botaoHelp.setFocusPainted(false);
        botaoHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHelpActionPerformed(evt);
            }
        });
        telaInicial.add(botaoHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 30, 40));

        botaoPlay.setBackground(new java.awt.Color(246, 110, 21));
        botaoPlay.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        botaoPlay.setForeground(new java.awt.Color(238, 240, 242));
        botaoPlay.setText("play");
        botaoPlay.setBorder(null);
        botaoPlay.setFocusPainted(false);
        botaoPlay.setRolloverEnabled(false);
        botaoPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlayActionPerformed(evt);
            }
        });
        telaInicial.add(botaoPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 240, 60));

        labelBackgroundTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/telainicial.png"))); // NOI18N
        telaInicial.add(labelBackgroundTelaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        painelPrincipal.add(telaInicial, "telaInicial");

        telaDashBoard.setAlignmentX(0.0F);
        telaDashBoard.setAlignmentY(0.0F);
        telaDashBoard.setMaximumSize(getPreferredSize());
        telaDashBoard.setMinimumSize(getPreferredSize());
        telaDashBoard.setPreferredSize(getPreferredSize());
        telaDashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 135, 30));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Torneios");
        telaDashBoard.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 386, 182, 54));

        menuInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/menuIcon.png"))); // NOI18N
        menuInicial.setAlignmentY(0.0F);
        menuInicial.setContentAreaFilled(false);
        telaDashBoard.add(menuInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 48, 48));

        jButton3.setBackground(new java.awt.Color(75, 150, 187));
        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Loja");
        telaDashBoard.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 386, 182, 54));

        botaoPerfil.setBackground(new java.awt.Color(228, 56, 82));
        botaoPerfil.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        botaoPerfil.setForeground(new java.awt.Color(255, 255, 255));
        botaoPerfil.setText("Perfil");
        botaoPerfil.setAlignmentY(0.0F);
        telaDashBoard.add(botaoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 100, 31));

        jButton5.setBackground(new java.awt.Color(255, 135, 30));
        jButton5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Partida Rápida");
        telaDashBoard.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 182, 54));

        botaoGaloDex.setBackground(new java.awt.Color(228, 56, 82));
        botaoGaloDex.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        botaoGaloDex.setForeground(new java.awt.Color(255, 255, 255));
        botaoGaloDex.setText("GaloDex");
        botaoGaloDex.setAlignmentY(0.0F);
        telaDashBoard.add(botaoGaloDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 83, 100, 31));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dash.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        telaDashBoard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        painelPrincipal.add(telaDashBoard, "telaDashBoard");

        telaLoja.setAlignmentX(0.0F);
        telaLoja.setAlignmentY(0.0F);
        telaLoja.setMaximumSize(getPreferredSize());
        telaLoja.setMinimumSize(getPreferredSize());

        javax.swing.GroupLayout telaLojaLayout = new javax.swing.GroupLayout(telaLoja);
        telaLoja.setLayout(telaLojaLayout);
        telaLojaLayout.setHorizontalGroup(
            telaLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        telaLojaLayout.setVerticalGroup(
            telaLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        painelPrincipal.add(telaLoja, "telaLoja");

        telaBatalha.setAlignmentX(0.0F);
        telaBatalha.setAlignmentY(0.0F);
        telaBatalha.setMaximumSize(getPreferredSize());
        telaBatalha.setMinimumSize(getPreferredSize());

        javax.swing.GroupLayout telaBatalhaLayout = new javax.swing.GroupLayout(telaBatalha);
        telaBatalha.setLayout(telaBatalhaLayout);
        telaBatalhaLayout.setHorizontalGroup(
            telaBatalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        telaBatalhaLayout.setVerticalGroup(
            telaBatalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        painelPrincipal.add(telaBatalha, "telaBatalha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        painelPrincipal.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoHelpActionPerformed

    private void botaoPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlayActionPerformed
        // botaoPlay encaminha a tela para o dashboard
        trocarTela("telaDashBoard");
    }//GEN-LAST:event_botaoPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGaloDex;
    private javax.swing.JButton botaoHelp;
    private javax.swing.JButton botaoPerfil;
    private javax.swing.JButton botaoPlay;
    private javax.swing.JButton botaoSettings;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBackgroundTelaInicial;
    private javax.swing.JButton menuInicial;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel telaBatalha;
    private javax.swing.JPanel telaDashBoard;
    private javax.swing.JPanel telaInicial;
    private javax.swing.JPanel telaLoja;
    // End of variables declaration//GEN-END:variables
}
