package com.rinha.gui;

import com.rinha.ataque.Ataque;
import com.rinha.perfil.Perfil;
import javax.swing.JProgressBar;

public class PainelBatalha extends PainelFilho{
    int usuarioAtq = 0;
    
    public PainelBatalha(MainFrame mainFrame, Perfil player) {
        this.mainFrame = mainFrame;
        this.painelPrincipal = this.mainFrame.getPainelPrincipal();
        this.player = player;
        
        initComponents();
    }

    // Getters

    public JProgressBar getBarraVidaMaquina() {
        return barraVidaMaquina;
    }

    public void setBarraVidaMaquina(JProgressBar barraVidaMaquina) {
        this.barraVidaMaquina = barraVidaMaquina;
    }

    public JProgressBar getBarraVidaPlayer() {
        return barraVidaPlayer;
    }

    public void setBarraVidaPlayer(JProgressBar barraVidaPlayer) {
        this.barraVidaPlayer = barraVidaPlayer;
    }
    
    // Atualizações da interface
    
    public void updateLabelsPPeNomeAtaque(){
        // Atualiza label do pp e do nome do ataque
        Ataque ataque;
        if (usuarioAtq != 0){
            // Nome do ataque
            ataque = this.mainFrame.getBatalhaAtual().getPlayer().getAtaque(usuarioAtq);
            this.labelPP.setText("PP: " + ataque.getPontosDePoderAtual());
            this.labelNomeAtq.setText(ataque.getNomeAtaque());
        }
        else {
            // Caso ainda não haja ataque selecionado
            this.labelNomeAtq.setText("Selecione o Ataque");
            this.labelPP.setText("");
        }
        // Botoes dos ataques dos galos
        botaoAtqBasico.setText(this.mainFrame.getBatalhaAtual().getPlayer().getAtaque(1).getNomeAtaque());
        botaoAtqTipificado.setText(this.mainFrame.getBatalhaAtual().getPlayer().getAtaque(2).getNomeAtaque());
        botaoAtqAgil.setText(this.mainFrame.getBatalhaAtual().getPlayer().getAtaque(3).getNomeAtaque());
        botaoAtqUltimate.setText(this.mainFrame.getBatalhaAtual().getPlayer().getAtaque(4).getNomeAtaque());
    }
    
    public void updateLabelsFoto(){
        // Atualiza as fotos de batalha dos Galos
        labelFotoMaquina.setIcon(this.mainFrame.getBatalhaAtual().getMaquina().getFotoBatalha());
        labelFotoPlayer.setIcon(this.mainFrame.getBatalhaAtual().getPlayer().getFotoBatalha());
    }
    
    public void updateBarrasVida(){
        // Atualização das barras de vida e das labels com o valor
        this.barraVidaMaquina.setValue(this.mainFrame.getBatalhaAtual().getMaquina().getPercentualVidaAtual());
        this.labelVidaMaquina.setText(Integer.toString(this.mainFrame.getBatalhaAtual().getMaquina().getVidaAtual()));
        this.barraVidaPlayer.setValue(this.mainFrame.getBatalhaAtual().getPlayer().getPercentualVidaAtual());
        this.labelVidaPlayer.setText(Integer.toString(this.mainFrame.getBatalhaAtual().getPlayer().getVidaAtual()));
    }
    
    public void updateInfoTelaBatalha(){
        // Atualiza as informações da tela de batalha
        this.updateLabelsPPeNomeAtaque();
        this.updateLabelsFoto();
        this.updateBarrasVida();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFotoPlayer = new javax.swing.JLabel();
        painelFuncoesAtaque = new javax.swing.JPanel();
        botaoAtqBasico = new javax.swing.JButton();
        botaoAtqTipificado = new javax.swing.JButton();
        botaoAtqUltimate = new javax.swing.JButton();
        botaoAtqAgil = new javax.swing.JButton();
        botaoAtacar = new javax.swing.JButton();
        labelPP = new javax.swing.JLabel();
        labelNomeAtq = new javax.swing.JLabel();
        labelFotoMaquina = new javax.swing.JLabel();
        barraVidaMaquina = new javax.swing.JProgressBar();
        barraVidaPlayer = new javax.swing.JProgressBar();
        labelNomePlayer = new javax.swing.JLabel();
        labelNomeMaquina = new javax.swing.JLabel();
        botaoDesistir = new javax.swing.JButton();
        labelVidaPlayer = new javax.swing.JLabel();
        labelVidaMaquina = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(labelFotoPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 150));

        painelFuncoesAtaque.setBackground(new java.awt.Color(238, 240, 242));

        botaoAtqBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtqBasicoActionPerformed(evt);
            }
        });

        botaoAtqTipificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtqTipificadoActionPerformed(evt);
            }
        });

        botaoAtqUltimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtqUltimateActionPerformed(evt);
            }
        });

        botaoAtqAgil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtqAgilActionPerformed(evt);
            }
        });

        botaoAtacar.setText("Atacar");
        botaoAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtacarActionPerformed(evt);
            }
        });

        labelPP.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelPP.setText("PP:");
        labelPP.setAlignmentY(0.0F);

        labelNomeAtq.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelNomeAtq.setText("Ataque");

        javax.swing.GroupLayout painelFuncoesAtaqueLayout = new javax.swing.GroupLayout(painelFuncoesAtaque);
        painelFuncoesAtaque.setLayout(painelFuncoesAtaqueLayout);
        painelFuncoesAtaqueLayout.setHorizontalGroup(
            painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFuncoesAtaqueLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAtqTipificado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtqBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAtqAgil, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtqUltimate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPP)
                    .addComponent(labelNomeAtq)
                    .addComponent(botaoAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFuncoesAtaqueLayout.setVerticalGroup(
            painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFuncoesAtaqueLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botaoAtqAgil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoAtqBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFuncoesAtaqueLayout.createSequentialGroup()
                        .addComponent(labelNomeAtq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(painelFuncoesAtaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtqTipificado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtqUltimate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        add(painelFuncoesAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 720, 160));

        labelFotoMaquina.setMaximumSize(new java.awt.Dimension(140, 140));
        labelFotoMaquina.setMinimumSize(new java.awt.Dimension(140, 140));
        labelFotoMaquina.setPreferredSize(new java.awt.Dimension(140, 140));
        add(labelFotoMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 140, 140));
        add(barraVidaMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 200, 20));
        add(barraVidaPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 20));

        labelNomePlayer.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        add(labelNomePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        labelNomeMaquina.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        add(labelNomeMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        botaoDesistir.setBackground(new java.awt.Color(228, 56, 82));
        botaoDesistir.setText("Desistir");
        botaoDesistir.setToolTipText("");
        botaoDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesistirActionPerformed(evt);
            }
        });
        add(botaoDesistir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        labelVidaPlayer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(labelVidaPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 40, -1));

        labelVidaMaquina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVidaMaquina.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(labelVidaMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 40, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void botaoAtqBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtqBasicoActionPerformed
        // Seleciona o Atq1 para o usarioAtq (Ataque Basico)
        usuarioAtq = 1;
        updateLabelsPPeNomeAtaque();
    }//GEN-LAST:event_botaoAtqBasicoActionPerformed

    private void botaoAtqTipificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtqTipificadoActionPerformed
        // Seleciona o Atq2 para o usarioAtq (Ataque Tipificado)
        usuarioAtq = 2;
        updateLabelsPPeNomeAtaque();
    }//GEN-LAST:event_botaoAtqTipificadoActionPerformed

    private void botaoAtqUltimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtqUltimateActionPerformed
        // Seleciona o Atq4 para o usarioAtq (Ataque Ultimate)
        usuarioAtq = 4;
        updateLabelsPPeNomeAtaque();
    }//GEN-LAST:event_botaoAtqUltimateActionPerformed

    private void botaoAtqAgilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtqAgilActionPerformed
        // Seleciona o Atq3 para o usarioAtq (Ataque Agil)
        usuarioAtq = 3;
        updateLabelsPPeNomeAtaque();
    }//GEN-LAST:event_botaoAtqAgilActionPerformed

    private void botaoAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtacarActionPerformed
        // Variável de controle para a maquina aguardar a vez
        boolean turnoMaquina = false;

        if (usuarioAtq != 0){
            turnoMaquina = this.mainFrame.getBatalhaAtual().turnoPlayer(usuarioAtq);
        }
        System.out.println(turnoMaquina);
        if (turnoMaquina){
            this.mainFrame.getBatalhaAtual().turnoMaquina();
        }
        // Atualiza as informações
        this.usuarioAtq = 0;
        updateInfoTelaBatalha();
    }//GEN-LAST:event_botaoAtacarActionPerformed

    private void botaoDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesistirActionPerformed
        // Sai da tela de batalha para tela dashboard
        this.trocarTela("dashboard");
        this.mainFrame.batalhaAtual.desistir();
    }//GEN-LAST:event_botaoDesistirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraVidaMaquina;
    private javax.swing.JProgressBar barraVidaPlayer;
    private javax.swing.JButton botaoAtacar;
    private javax.swing.JButton botaoAtqAgil;
    private javax.swing.JButton botaoAtqBasico;
    private javax.swing.JButton botaoAtqTipificado;
    private javax.swing.JButton botaoAtqUltimate;
    private javax.swing.JButton botaoDesistir;
    private javax.swing.JLabel labelFotoMaquina;
    private javax.swing.JLabel labelFotoPlayer;
    private javax.swing.JLabel labelNomeAtq;
    private javax.swing.JLabel labelNomeMaquina;
    private javax.swing.JLabel labelNomePlayer;
    private javax.swing.JLabel labelPP;
    private javax.swing.JLabel labelVidaMaquina;
    private javax.swing.JLabel labelVidaPlayer;
    private javax.swing.JPanel painelFuncoesAtaque;
    // End of variables declaration//GEN-END:variables
}
