package com.rinha.gui;

import com.rinha.loja.Loja;
import com.rinha.perfil.Perfil;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class PainelLoja extends PainelFilho {
    Loja loja;
    
    public PainelLoja(mainFrame mainFrame, Perfil player) {
        this.mainFrame = mainFrame;
        this.painelPrincipal = mainFrame.getPainelPrincipal();
        this.player = player;
        this.loja = mainFrame.loja;
        initComponents();
    }
    
    // Getters

    public Loja getLoja() {
        return loja;
    }

    public JButton getBotaoComprarMilho() {
        return botaoComprarMilho;
    }

    public JButton getBotaoComprarPocao() {
        return botaoComprarPocao;
    }

    public JButton getBotaoVoltarLoja() {
        return botaoVoltarLoja;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public JLabel getLabelSaldoCarteira() {
        return labelSaldoCarteira;
    }

    public JTable getTableMilhosLoja() {
        return tableMilhosLoja;
    }

    public JTable getTablePocoesLoja() {
        return tablePocoesLoja;
    }
    
    
    // Atualizações da interface
    public void updateInfoGalo(){
        this.labelFotoGaloLoja.setIcon(this.loja.getGalo().getFotoBatalha());
        this.labelInfoGaloLoja.setText(this.loja.getGalo().getNome()+ " R$ " + this.loja.getGalo().getValor());
    }
    
    public void updateTablePocoesLoja(){
        DefaultTableModel table = (DefaultTableModel) this.tablePocoesLoja.getModel();
        table.setRowCount(0);
        int tamanho = this.loja.getQuantidadePocoes();
        for (int index = 0; index < tamanho; index++){
            Object[] dados = this.loja.getInfoPocoes(index);
            table.addRow(dados);
        }
    }
    
    public void updateTableMilhosLoja(){
        DefaultTableModel table = (DefaultTableModel) this.tableMilhosLoja.getModel();
        table.setRowCount(0);
        int tamanho = loja.getQuantidadeMilhos();
        for (int index = 0; index < tamanho; index++){
            Object[] dados = loja.getInfoMilhos(index);
            table.addRow(dados);
        }
    }
    
    public void updateSaldo(){
        this.labelSaldoCarteira.setText(Integer.toString(player.getCarteira().getSaldo()));
    }
    
    public void updateInfoTelaLoja(){
        this.updateSaldo();
        this.updateInfoGalo();
        this.updateTableMilhosLoja();
        this.updateTablePocoesLoja();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltarLoja = new javax.swing.JButton();
        labelSaldoCarteira = new javax.swing.JLabel();
        tabbedMilhoePocaoLoja = new javax.swing.JTabbedPane();
        painelMilhosLoja = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMilhosLoja = new javax.swing.JTable();
        botaoComprarMilho = new javax.swing.JButton();
        painelPocoesLoja = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePocoesLoja = new javax.swing.JTable();
        botaoComprarPocao = new javax.swing.JButton();
        labelFotoGaloLoja = new javax.swing.JLabel();
        labelInfoGaloLoja = new javax.swing.JLabel();
        botaoComprarGalo = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltarLoja.setText("Voltar");
        botaoVoltarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarLojaActionPerformed(evt);
            }
        });
        add(botaoVoltarLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        labelSaldoCarteira.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelSaldoCarteira.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSaldoCarteira.setText("Tua Grana");
        add(labelSaldoCarteira, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 110, -1));

        tableMilhosLoja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Xp", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableMilhosLoja);

        botaoComprarMilho.setText("Comprar");
        botaoComprarMilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarMilhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelMilhosLojaLayout = new javax.swing.GroupLayout(painelMilhosLoja);
        painelMilhosLoja.setLayout(painelMilhosLojaLayout);
        painelMilhosLojaLayout.setHorizontalGroup(
            painelMilhosLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(botaoComprarMilho, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        painelMilhosLojaLayout.setVerticalGroup(
            painelMilhosLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMilhosLojaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(botaoComprarMilho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedMilhoePocaoLoja.addTab("Milhos", painelMilhosLoja);

        tablePocoesLoja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restauração", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePocoesLoja);

        botaoComprarPocao.setText("Comprar");
        botaoComprarPocao.setToolTipText("");
        botaoComprarPocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarPocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPocoesLojaLayout = new javax.swing.GroupLayout(painelPocoesLoja);
        painelPocoesLoja.setLayout(painelPocoesLojaLayout);
        painelPocoesLojaLayout.setHorizontalGroup(
            painelPocoesLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(botaoComprarPocao, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        painelPocoesLojaLayout.setVerticalGroup(
            painelPocoesLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPocoesLojaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(botaoComprarPocao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedMilhoePocaoLoja.addTab("Poções de Cura", painelPocoesLoja);

        add(tabbedMilhoePocaoLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, 270));

        labelFotoGaloLoja.setMaximumSize(new java.awt.Dimension(150, 150));
        labelFotoGaloLoja.setMinimumSize(new java.awt.Dimension(150, 150));
        labelFotoGaloLoja.setPreferredSize(new java.awt.Dimension(150, 150));
        add(labelFotoGaloLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        labelInfoGaloLoja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelInfoGaloLoja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfoGaloLoja.setText("Nome Galo e Preço");
        labelInfoGaloLoja.setToolTipText("");
        add(labelInfoGaloLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 250, -1));

        botaoComprarGalo.setText("Comprar");
        botaoComprarGalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarGaloActionPerformed(evt);
            }
        });
        add(botaoComprarGalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 250, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarLojaActionPerformed
        // Volta da loja pro Dashboard
        trocarTela("dashboard");
        this.mainFrame.painelDashboard.updateTelaDashboard();
        this.loja = new Loja(20);
        this.botaoComprarGalo.setVisible(true);
    }//GEN-LAST:event_botaoVoltarLojaActionPerformed

    private void botaoComprarPocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarPocaoActionPerformed
        // Botao para compra de Pocoes
        int index = this.tablePocoesLoja.getSelectedRow();
        boolean sucess = loja.venderPocaoCura(this.player, index);
        System.out.println(sucess);
        this.updateInfoTelaLoja();
    }//GEN-LAST:event_botaoComprarPocaoActionPerformed

    private void botaoComprarMilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarMilhoActionPerformed
        // Botao para compra de Milhos
        int index = this.tableMilhosLoja.getSelectedRow();
        boolean sucess = this.loja.venderMilho(player, index);
        System.out.println(sucess);
        this.updateInfoTelaLoja();
    }//GEN-LAST:event_botaoComprarMilhoActionPerformed

    private void botaoComprarGaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarGaloActionPerformed
        // Botao para comprar o galo
        boolean sucess = this.loja.venderGalo(player);
        if (sucess){
            this.botaoComprarGalo.setVisible(false);
        }
        this.labelSaldoCarteira.setText(Integer.toString(player.getCarteira().getSaldo()));
        System.out.println(sucess);
    }//GEN-LAST:event_botaoComprarGaloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoComprarGalo;
    private javax.swing.JButton botaoComprarMilho;
    private javax.swing.JButton botaoComprarPocao;
    private javax.swing.JButton botaoVoltarLoja;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFotoGaloLoja;
    private javax.swing.JLabel labelInfoGaloLoja;
    private javax.swing.JLabel labelSaldoCarteira;
    private javax.swing.JPanel painelMilhosLoja;
    private javax.swing.JPanel painelPocoesLoja;
    private javax.swing.JTabbedPane tabbedMilhoePocaoLoja;
    private javax.swing.JTable tableMilhosLoja;
    private javax.swing.JTable tablePocoesLoja;
    // End of variables declaration//GEN-END:variables
}
