package com.rinha.gui;

import com.rinha.galos.Galinheiro;
import com.rinha.galos.Galo;
import com.rinha.perfil.Perfil;
import com.rinha.torneio.Torneio;
import java.util.ArrayList;

public class PainelTorneios extends PainelFilho {
    public PainelTorneios(mainFrame mainFrame, Perfil player){
        this.mainFrame = mainFrame;
        this.painelPrincipal = mainFrame.getPainelPrincipal();
        this.player = player;
        
        initComponents();
    }
    
    public void iniciarNovoTorneio(ArrayList<Galo> inimigos){
        this.mainFrame.torneioAtual = new Torneio(this.mainFrame.player, inimigos);
        this.mainFrame.torneioAtual.nextRodada();
        this.mainFrame.batalhaAtual = this.mainFrame.torneioAtual.getBatalhaAtual();
        this.mainFrame.painelProximaBatalha.abrirProximaBatalha();
        this.mainFrame.painelBatalha.updateInfoTelaBatalha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoTorneioRaro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoTorneioRaro.setText("Torneio Raro");
        botaoTorneioRaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTorneioRaroActionPerformed(evt);
            }
        });
        add(botaoTorneioRaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 280, 80));

        jButton2.setText("Torneio dos Campeões");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 280, 80));

        jButton3.setText("Torneio Épico");
        jButton3.setAlignmentY(0.0F);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 80));

        jButton4.setText("Torneio Lendário");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 280, 80));

        jButton5.setText("Torneio Fofa");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 280, 80));

        jButton6.setText("Torneio Final");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 280, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTorneioRaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTorneioRaroActionPerformed
        ArrayList<Galo> inimigos = new Galinheiro().gerarGalosRaros(2);
        this.iniciarNovoTorneio(inimigos);
    }//GEN-LAST:event_botaoTorneioRaroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoTorneioRaro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables
}
