package com.rinha.gui;

import com.rinha.galos.Galinheiro;
import com.rinha.galos.Galo;
import com.rinha.perfil.Perfil;
import com.rinha.torneio.Torneio;
import java.util.ArrayList;

public class PainelTorneios extends PainelFilho {
    public PainelTorneios(mainFrame mainFrame, Perfil player){
        this.mainFrame = mainFrame;
        this.painelPrincipal = mainFrame.getPainelPrincipal();
        this.player = player;
        
        initComponents();
    }
    
    public void iniciarNovoTorneio(ArrayList<Galo> inimigos){
        this.mainFrame.torneioAtual = new Torneio(this.mainFrame.player, inimigos);
        this.mainFrame.torneioAtual.nextRodada();
        this.mainFrame.batalhaAtual = this.mainFrame.torneioAtual.getBatalhaAtual();
        this.mainFrame.painelProximaBatalha.abrirProximaBatalha();
        this.mainFrame.painelBatalha.updateInfoTelaBatalha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoTorneioRaro = new javax.swing.JButton();
        botaoTorneioCampeoes = new javax.swing.JButton();
        botaoTorneioEpico = new javax.swing.JButton();
        botaoTorneioLendario = new javax.swing.JButton();
        botaoTorneioFofa = new javax.swing.JButton();
        botaoTorneioFinal = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoTorneioRaro.setText("Torneio Raro");
        botaoTorneioRaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTorneioRaroActionPerformed(evt);
            }
        });
        add(botaoTorneioRaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 280, 80));

        botaoTorneioCampeoes.setText("Torneio dos Campeões");
        add(botaoTorneioCampeoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 280, 80));

        botaoTorneioEpico.setText("Torneio Épico");
        botaoTorneioEpico.setAlignmentY(0.0F);
        botaoTorneioEpico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTorneioEpicoActionPerformed(evt);
            }
        });
        add(botaoTorneioEpico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 80));

        botaoTorneioLendario.setText("Torneio Lendário");
        botaoTorneioLendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTorneioLendarioActionPerformed(evt);
            }
        });
        add(botaoTorneioLendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 280, 80));

        botaoTorneioFofa.setText("Torneio Fofa");
        add(botaoTorneioFofa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 280, 80));

        botaoTorneioFinal.setText("Torneio Final");
        add(botaoTorneioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 280, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTorneioRaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTorneioRaroActionPerformed
        ArrayList<Galo> inimigos = new Galinheiro().gerarGalosRaros(2);
        this.iniciarNovoTorneio(inimigos);
    }//GEN-LAST:event_botaoTorneioRaroActionPerformed

    private void botaoTorneioEpicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTorneioEpicoActionPerformed
        ArrayList<Galo> inimigos = new Galinheiro().gerarGalosEpicos(2);
        this.iniciarNovoTorneio(inimigos);
    }//GEN-LAST:event_botaoTorneioEpicoActionPerformed

    private void botaoTorneioLendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTorneioLendarioActionPerformed
        ArrayList<Galo> inimigos = new Galinheiro().gerarGalosLendarios(2);
        this.iniciarNovoTorneio(inimigos);
    }//GEN-LAST:event_botaoTorneioLendarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoTorneioCampeoes;
    private javax.swing.JButton botaoTorneioEpico;
    private javax.swing.JButton botaoTorneioFinal;
    private javax.swing.JButton botaoTorneioFofa;
    private javax.swing.JButton botaoTorneioLendario;
    private javax.swing.JButton botaoTorneioRaro;
    // End of variables declaration//GEN-END:variables
}
