/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rinha.gui;

/**
 *
 * @author ratolar
 */
public class Play extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Play() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoPlay = new javax.swing.JButton();
        labelRinhaNome = new javax.swing.JLabel();
        labelBackgroundTelaInicial = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoPlay.setBackground(new java.awt.Color(246, 110, 21));
        botaoPlay.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        botaoPlay.setForeground(new java.awt.Color(238, 240, 242));
        botaoPlay.setText("play");
        botaoPlay.setBorder(null);
        botaoPlay.setFocusPainted(false);
        botaoPlay.setRolloverEnabled(false);
        botaoPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlayActionPerformed(evt);
            }
        });
        add(botaoPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 200, 50));

        labelRinhaNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/nomerinha.png"))); // NOI18N
        add(labelRinhaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 240, 90));

        labelBackgroundTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/telaInicial.gif"))); // NOI18N
        add(labelBackgroundTelaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlayActionPerformed
        // botaoPlay encaminha a tela para o dashboard
        //trocarTela("telaBemVindo");
        this.trocarTela("store");
        galosIniciais = galinheiro.gerarGalosIniciais();

    }//GEN-LAST:event_botaoPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPlay;
    private javax.swing.JLabel labelBackgroundTelaInicial;
    private javax.swing.JLabel labelRinhaNome;
    // End of variables declaration//GEN-END:variables
}
